version: '3.7'
services:
  node:
    build: .
    image: trello:ts-rest
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    # entrypoint: ["./entrypoint.sh"]
    environment:
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    env_file:
      - .env
    volumes:
      - logs:/usr/app/logs
      - ./src:/usr/app/src
      - ./uploads:/usr/app/uploads
    restart: always
    networks:
        - back
  postgres:
    build: ./database/
    image: trello:postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    # command: -p ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${POSTGRES_PORT}
    volumes:
      - database:/var/lib/postgresql/data
    restart: always 
    networks:
        - back
volumes:
  logs:
  database:
networks:
  back:
    driver: bridge
    ipam: 
      config:
            - subnet: 172.16.238.0/24
              gateway: 172.16.238.1